micronaut:
  application:
    name: backend
    version: "0.1.0"
    fortunesUrl: ${FORTUNES_URL:`https://raw.githubusercontent.com/bmc/fortunes/master/fortunes`}
endpoints:
  health:
    enabled: true
datasources:
  default:
    url: jdbc:mysql://${DATABASE_HOST:`localhost`}:${DATABASE_PORT:`3306`}/${DATABASE_DATABASE:`db`}
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${DATABASE_USER:root}
    password: ${DATABASE_PASSWORD}
    dialect: MYSQL
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl.auto: validate
      show_sql: true
flyway:
  datasources:
    default:
      enabled: true
