micronaut:
  application:
    name: backend
    version: "0.1.0"
    fortunesUrl: "https://raw.githubusercontent.com/bmc/fortunes/master/fortunes"
endpoints:
  health:
    enabled: true
datasources:
#  default:
#    url: jdbc:mariadb://localhost:3306/db
#    driverClassName: org.mariadb.jdbc.Driver
#    username: root
#    password: ''
#    schema-generate: CREATE_DROP
#    dialect: MYSQL
  default:
    url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    schema-generate: CREATE_DROP
    dialect: H2
jpa.default.properties.hibernate.hbm2ddl.auto: update
